### ISSUE TITLE
Relationship between HausKeepr and Client and Reviews

### ISSUE THREAD

**Issue by nellirism** [patricklago21/hausKeepr#31]
User Stories

* Make sure that when a client clicks on Book Me, a new page will appear with the Hauskeepr profile. (this is already done.)

* The hauskeepr profile will have to display the name of the reviewer, the review and the rating that client provided. 

* Our issue is that the SequelizeEagerLoadingError which points to the relationship of the Client and the Hauskeepr thus, not allowing us to pull the Client Name and display with the Review as we pull the hauskeepr profile.

**Comment by acevezl** [comment]
Fixed!
